### ISSUE TITLE
qtwebengine_resources_100p.pak

### ISSUE THREAD

**Issue by Tealk** [michelolvera/vs-ghostwriter#10]
I have linked .me files with ghostwriter and whenever I open a file a debug.log is created next to it.

v1.8.0
debug.log
```
[0828/073033.571:ERROR:resource_bundle.cc(815)] Failed to load C:\Program Files\ghostwriter\qtwebengine_resources_100p.pak
Some features may not be available.
[0828/073033.575:ERROR:resource_bundle.cc(815)] Failed to load C:\Program Files\ghostwriter\qtwebengine_resources_200p.pak
Some features may not be available.
[0828/073034.190:ERROR:resource_bundle.cc(815)] Failed to load C:\Program Files\ghostwriter\qtwebengine_resources_100p.pak
Some features may not be available.
[0828/073034.194:ERROR:resource_bundle.cc(815)] Failed to load C:\Program Files\ghostwriter\qtwebengine_resources_200p.pak
Some features may not be available.
```

https://github.com/wereturtle/ghostwriter/issues/457

**Comment by netapau** [comment]
@michelolvera with __ghostwriter Version 1.8.0 and QtWebEngine__ 
### Deploying Resources
Qt WebEngine requires the following resource files:

- qtwebengine_resources.pak contains the resources needed by Chromium.
- qtwebengine_devtools_resources.pak contains tools for remote debugging.
- **qtwebengine_resources_100p.pak** contains images suitable for low resolution displays.
- **qtwebengine_resources_200p.pak** contains images suitable for high DPI displays.
- icudtl.dat provides support for International Components for Unicode (ICU). It is the Chromium version of ICU, which is not needed if Qt WebEngine was configured to use the system ICU.

See [qtwebengine-deploying at Qt website](https://doc.qt.io/qt-5/qtwebengine-deploying.html) 

Maybe can you help

**Comment by netapau** [comment]
I did a test with the files qtwebengine_resources_100p.pak and qtwebengine_resources_200p.pak, I think it works well.
See :
https://github.com/netapau/vs-ghostwriter/releases

**Comment by michelolvera** [comment]
Today or tomorrow I will upload a new installer with Qt updated to version 5.13.1

**Comment by michelolvera** [comment]
Done!
