### ISSUE TITLE
Why not a 32bit version?

### ISSUE THREAD

**Issue by Nils85** [michelolvera/vs-ghostwriter#11]
Is there something that doesn't works with the 32bit compilation?

**Comment by JohnTHaller** [comment]
We'd love to see a 32-bit version so we can package it at PortableApps.com. It's necessary for folks with 32-bit machines (mostly Windows 7) and for folks with new Windows ARM tablets which can run 32-bit Windows apps but not 64-bit Windows apps.

**Comment by michelolvera** [comment]
I'll work on it.
