### ISSUE TITLE
Fullscreen mode slowdown on a 144Hz monitor

### ISSUE THREAD

**Issue by Timecrash** [michelolvera/vs-ghostwriter#14]
I'm not sure how to document this, however I've noticed when I try to use fullscreen mode on my 144Hz monitor, the app slows down drastically. I can still navigate using keys, however the mouse movement is sluggish. Might just be the monitor, though; I've had this happen with a few other apps.

**Comment by michelolvera** [comment]
That's weird, do those other applications also use Qt as development framwork?
Is the same with Linux?
