### ISSUE TITLE
Option to Ignore YAML Front Matter in HTML Preview

### ISSUE THREAD

**Issue by bredd** [michelolvera/vs-ghostwriter#15]
When building GitHub pages, you often put front matter in YAML format at the beginning of a MarkDown document. When doing this, the first line of the file MUST be three hyphens. Then you have the YAML front matter, then another line with just three hyphens, and then the balance of the document in MarkDown format. (See [https://jekyllrb.com/docs/front-matter/](https://jekyllrb.com/docs/front-matter/) ). 

It would be nice if there was an option to ignore the front matter, or give it special formatting, in the preview pane.

Should this be posted to the master GhostWriter project or is this a perpetual fork?

**Comment by michelolvera** [comment]
I'm sorry, it is very difficult for me due to time constraints to add new features, but you are free to send a pull request adding the functions you require.

**Comment by bredd** [comment]
I will consider that... when I have a little more time. Thanks!
