### ISSUE TITLE
Minor bug: "Export failed: --smart/-S has been removed."

### ISSUE THREAD

**Issue by PrSunflower** [michelolvera/vs-ghostwriter#16]
## Issue with Toshiba Satellite laptop

Sometimes when opening Ghostwriter, in the HTML preview panel it is written in bold red: 

```
Export failed: --smart/-S has been removed. Use +smart or -smart extension instead. For example: pandoc -f markdown+smart -t markdown-smart. Try pandoc --help for more information.
```

![Export_failed_Screenshot](https://user-images.githubusercontent.com/59576952/72006745-906c2380-3250-11ea-8383-c0fb0cc1f80e.png)

### Frequency

- 8 Jan
- 10 Mar
- 20 Mar
- 20 Apr
- ...

### Solution

Closing and re-opening Ghostwriter fixes the problem, everything goes back to normal.

### System info

- Windows 10 Home version 1909 (64-bit)
- Ghostwriter versions 1.8.0 and 1.8.1 portable

<br>
<br>

## Issue with Dell Latitude laptop

Same problem, **happens every time**:

![image](https://user-images.githubusercontent.com/59576952/93997572-d68ff580-fd93-11ea-9fe4-81da58d3c112.png)

### When did it happen

It happened after I installed Pandoc (Windows 64-bit), restarted Ghostwriter and chose any Pandoc preview option. If I choose `Sundown` there never is an error.

### No solutions

Closing and reopening Ghostwriter did not work this time. Restarting the computer did not work either! 😮

### System info

- Windows 10 Pro version 2004 (64-bit)
- Ghostwriter version 1.8.1 portable

<br>

### Thanks!

I would like to thank the developer and collaborators for this simple, beautiful, feature-rich free software.

**Comment by PrSunflower** [comment]
Here is a screenshot I took some minutes ago after having booted up my computer:
![Export_failed_Screenshot](https://user-images.githubusercontent.com/59576952/72006745-906c2380-3250-11ea-8383-c0fb0cc1f80e.png)

**Comment by michelolvera** [comment]
Hi, could you tell me if this error still occurs in version 1.8.1? Thank you.

**Comment by PrSunflower** [comment]
@michelolvera Hello, thank you for answering.

I saw your answer the day you wrote it but I wanted to test the program on a long run before replying.

It has now been more than 1 week that I use Ghostwriter 1.8.1 portable everyday and everything was fine... until 2 minutes ago! Sadly I just got the same error: <span style="color:red">**"Export failed: --smart/-S has been removed. Use +smart or -smart extension instead. For example: pandoc -f markdown+smart -t markdown-smart. Try pandoc --help for more information."**</span>

![image](https://user-images.githubusercontent.com/59576952/77163058-9d598e80-6aad-11ea-9e1c-d0da18beba91.png)

Again restarting helped:
![image](https://user-images.githubusercontent.com/59576952/77163143-c2e69800-6aad-11ea-94bb-dd5e8a4d7054.png)


I am quite surprised that the error appeared again, for 10 days it seemed to work seamlessly.

Thank you for your help on this issue.

**Comment by PrSunflower** [comment]
Hmmmm funny....

I have just had the same error again and it has been exactly one month since the last time it happened.

Happening once in a month, it is in deed a "minor" bug! 😄

**Comment by PrSunflower** [comment]
_**As a side note:**_

I have switched to Debian 10 and I am using Ghostwriter on GNU/Linux since 2 months now, this error has never happened (I am using the same computer).

So I am getting it only on Windows and it doesn't seem to be linked to my hardware.

**Comment by PrSunflower** [comment]
**_Additional info 2:_**

I have been using Ghostwriter on a Windows 10 machine everyday since 2 months. This issue has never appeared.

**Comment by PrSunflower** [comment]
**_Additional info 3:_**

I just had the error on this other laptop I was talking about earlier 😅

![image](https://user-images.githubusercontent.com/59576952/93997572-d68ff580-fd93-11ea-9fe4-81da58d3c112.png)


<br>

### When did it happen

After I installed Pandoc (Windows 64-bit), restarted Ghostwriter (version 1.8.1 portable) and chose `Pandoc Github-flavoured Markdown` as a preview option. I was using `Sundown` previously.

**All Pandoc previews gave me the error.**

<br>

### How to solve the problem

Closing and reopening Ghostwriter did not work this time 😮

**Comment by PrSunflower** [comment]
23 Sep 2020: I have deleted some of my previous messages and updated the description. It should be shorter and clearer now.

**Comment by PrSunflower** [comment]
5 Nov 2020: For the first time this issue happened on Ghostwriter for GNU/Linux (on my Toshiba Satellite laptop).

"Export failed: --smart/-S has been removed. Use +smart or -smart extension instead. For example: pandoc -f markdown+smart -t markdown-smart. Try pandoc --help for more information."

I am going to write an issue on **wereturtle**'s repository. Maybe the problem is not Windows-only.

**Comment by PrSunflower** [comment]
Wereturtle has closed the issue because of the lack of knowledge on this error. If I have more information I'll post it in the issue mentionned above 😉
