### ISSUE TITLE
How to fix Ghostwriter not opening: "VCRUNTIME140_1.dll was not found." 

### ISSUE THREAD

**Issue by PrSunflower** [michelolvera/vs-ghostwriter#23]
### The problem

Hi, I did a clean reinstall of Windows on my computer recently which wiped out all my programs including Ghostwriter, and after that I downloaded _Ghostwriter 1.8.1_ (portable version), which I was using before reinstalling Windows.

However this time it refused to open, stating a missing .DLL

![scr1](https://user-images.githubusercontent.com/59576952/82588981-cc6aaa00-9b9b-11ea-8cb3-40e1c39a0998.png)

I managed to solve the problem and I am writing this "guide" in case someone else has the same problem. (I searched on this repository and on wereturtle's repository but no issues were mentioning this error) 

### Actions taken that DID NOT solve the problem

1. I re-downloaded the same portable version and extracted it in another location of my PC, I still had the same "VCRUNTIME" error.
2. I already had **"Microsoft Visual C++ 2017 - 14.14.26429"** and I decided to reinstall it. I still had the same "VCRUNTIME" error.

![scr2](https://user-images.githubusercontent.com/59576952/82589983-3b94ce00-9b9d-11ea-9ac4-2cbb0a1929cd.png)

### How I solved the problem

Instead of downloading the portable version I downloaded the installer of **Ghostwriter 1.8.0**, when launching it it automatically installed **"Microsoft Visual C++ 2015-2019 - 14.23.27820"**

![scr4](https://user-images.githubusercontent.com/59576952/82590574-36844e80-9b9e-11ea-80d2-8e4c91e41a7d.png)

After that I launched the portable version and it opened correctly with no error. ✔ 
Currently both the portable 1.8.1 version and the installed program 1.8.0 work correctly.

<br>

### Suggestions

@michelolvera Is it possible to mention in the README.md that in order to run the portable version **Microsoft Visual C++ 2015-2019 - 14.23.27820** is required please?

It took me some time to solve the issue because I couldn't find help anywhere on this repository.

**Comment by Geoff99** [comment]
Hi @PrSunflower ,

Thanks for this.  I have just encountered the same problem (Windows 10, version 1909), and tried your solution.  The 1.8.0 install worked fine (and now runs happily for me), but I still see the same error on the portable 1.8.1 version :-(

Usually I would do more digging on my pc, to try and help figure things out, but I've been using 1.8.0 happily enough up to now, and have lots to do resetting my pc up after repeated failed Windows 10 updates from version 1809 meant I had to do a clean install of Windows (mutter mutter ….)

PS Your issue documentation saved me heaps of time trying out dead ends myself !! Many thanks

**Comment by PrSunflower** [comment]
@Geoff99 
Hello, wow I wrote these instructions because I didn't want to keep them for myself, I wasn't expecting to help someone that quickly! 😃 (I forgot to mention I am also running **Windows 10 Home version 1909**)

> PS Your issue documentation saved me heaps of time trying out dead ends myself !! Many thanks

I am glad these instructions were useful to you, I'm not interested in coding but I am happy to help! 😄

> The 1.8.0 install worked fine (and now runs happily for me), but I still see the same error on the portable 1.8.1 version :-(

Oh really? That's strange. I checked my programs and I only have one version of **Microsoft Visual C++** (see below):

![image](https://user-images.githubusercontent.com/59576952/82668027-39804d00-9c39-11ea-993b-2527c186c2bf.png)

I re-downloaded the portable Ghostwriter 1.8.1 and it's running just fine:

![image](https://user-images.githubusercontent.com/59576952/82668110-5e74c000-9c39-11ea-825f-e3fa1a8e5b39.png)

I haven't done any more actions that I didn't mention in my previous comment. I don't know what's blocking your computer form running 1.8.1 😕  Maybe try to run the "Windows compatibility troubleshooter" to see if it can help?

> Usually I would do more digging on my pc, to try and help figure things out, but I've been using 1.8.0 happily enough up to now, and have lots to do resetting my pc up after repeated failed Windows 10 updates from version 1809 meant I had to do a clean install of Windows (mutter mutter ….)

Oh yes I see what you're going through 😂. Let's see the positive side: you're starting fresh with a new Windows, you can re-download only the programs you need and not other bloatware that you may have accumulated since many years!

**Comment by michelolvera** [comment]
Note added to README.md

**Comment by Geoff99** [comment]
Hi @PrSunflower 

Version 1.8.1 now works for me as well :-)

Not sure which bit of magic made the difference, but I did the following (after installing the 1.8.0 version, which worked first time)

* restarted my computer (no joy with 1.8.1)
* installed pandoc 2.9.2.1
* installed MikTex 2.9.7442
* ran the 1.8.0 version several times on a large md file (which resulted in an assortment of missing Latex packages being downloaded)
* finished for the day and switched the computer off overnight

And in the morning I decided to give version 1.8.1 another try, and it worked.  My guess (pure speculation) is that overnight Windows 10 reset/recovered something that probably ought to have happened - but didn't  - when I installed the 1.8.0 version.

Anyway, now I can get back to recovering all the other useful programs and utilities I've lost …

PS @michelolvera Before I forget - **many thanks** for maintaining this windows fork of ghostwriter, very much appreciated.

**Comment by PrSunflower** [comment]
@michelolvera Thank you very much!

@Geoff99 I am happy to read that everything is working fine for you now. Yes if you had not tried to restart your computer after installing VC++ that could have been what was blocking you.

When installing library packages, runtime environments or other programs that have a lot of dependencies it is a good habit to restart Windows before using them.
