### ISSUE TITLE
Microsoft Visual C++ is not required to avoid VCRUNTIME140_1.dll

### ISSUE THREAD

**Issue by chopin2712** [michelolvera/vs-ghostwriter#24]
Hello. This is a quick note. I saw that you wrote in the README that _Microsoft Visual C++ 2015-2019_ is required to install Ghostwriter.

I didn't wanted to install this software so I found a workaround for it. Simply download VCRUNTIME140_1.dll and add it into the folder where all the files are. 

Now Ghostwriter is able to recognize the DLL and everything should work properly! No need of any additional software other than 7ZIP and the archive :wink:

Hope that helps!

PS: I am going to do a pull request as well for this.

**Comment by PrSunflower** [comment]
Hi @chopin2712 👋

Yes the Readme.md was updated after my suggestion in #23. Is downloading .DLL files from the Internet safe? I thought I read multiple times that it was dangerous to use DLL files from unknown sources.
