### ISSUE TITLE
Hard-coded Qt path, project build Path

### ISSUE THREAD

**Issue by rolandog** [michelolvera/vs-ghostwriter#6]
Hi.

First, thank you very much for your efforts and for making this available.

I'm rather new to building C++ projects, so this might be on-me... 

However, at first my builds were failing because of the following two issues:

* Qt's path was set to `C:\Apps\Qt`, instead of the default installation location of `C:\Qt`
* (This one I don't know if there is any way around it) The path for the build location was also set to a local machine's username.
* Also, there was some extra information that doesn't need to be included in the solution (like PostgreSQL's location, etc.)

Finally, after correcting those paths (for my computer), I was able to build, but I wasn't able to run due to the executable not being able to find some Qt5 dlls; but I guess that might go on another bug.

**Comment by michelolvera** [comment]
I apologize for the inconvenience, the project was created using `qmake -tp vc`, maybe you prefer to try to compile with qmake without the need of VS2017/VS2019, if you know a better way to do it you can make a pull request.

Thank you.
