### ISSUE TITLE
Silent install

### ISSUE THREAD

**Issue by ironsketch** [michelolvera/vs-ghostwriter#8]
I am looking for the commands to run it silently. Our school is going to use this for science students and I will be needing to mass install this on our computers.

**Comment by michelolvera** [comment]
Working on it, it will take a couple of weeks, my work life is crazy. Thank you.

**Comment by ironsketch** [comment]
There is no rush. I ended up creating a Powershell script to do it. :D But this will still be helpful for others :D!!

**Comment by michelolvera** [comment]
DONE!
