### ISSUE TITLE
ghostwriter does not start

### ISSUE THREAD

**Issue by SCLeoX** [michelolvera/vs-ghostwriter#9]
I haven been using ghost writer for about half a year. Recently (about 2 or 3 weeks ago), ghostwriter stopped working for me. When I double click the icon, nothing happened but my cursor transforms to "busy" for a couple seconds before it transforms back. (ghostwriter does appear in task manager for a couple seconds and then it disappears.)

I have tried reinstalling ghostwriter with the installer and using the portable version. In both cases, the GUI just does not show up at all.

I am using Windows 10 Version 1903. I can't think of anything else to include in this issue. If you need anything else, please let me know.

**Comment by Timecrash** [comment]
I'm also having this problem. Here is the error message in the Event Viewer:
```
Faulting application name: ghostwriter.exe, version: 0.0.0.0, time stamp: 0x5ce3f39f
Faulting module name: ghostwriter.exe, version: 0.0.0.0, time stamp: 0x5ce3f39f
Exception code: 0xc000041d
Fault offset: 0x0000000000056b3c
Faulting process id: 0xee0
Faulting application start time: 0x01d559ae7219a3ba
Faulting application path: C:\Program Files\ghostwriter\ghostwriter.exe
Faulting module path: C:\Program Files\ghostwriter\ghostwriter.exe
Report Id: 607ce43d-f711-4e88-8910-d7da69121e1a
Faulting package full name: 
Faulting package-relative application ID: 
```

**Comment by michelolvera** [comment]
The installer and Qt version have been updated, could you try this version and tell me what the result was?

**Comment by SCLeoX** [comment]
> The installer and Qt version have been updated, could you try this version and tell me what the result was?

@michelolvera It still doesn't work

**Comment by Timecrash** [comment]
This worked for me.

**Comment by SCLeoX** [comment]
@Timecrash Wait, which binary are you using? I downloaded from release page, but it is from May.

**Comment by Timecrash** [comment]
I just went with the available one. I might have picked up the wrong
version, though.

**Comment by SCLeoX** [comment]
@michelolvera I tried both the installer and portable, and neither of them works. Is there anything I can do to help you diagnose the issue?

**Comment by michelolvera** [comment]
Ok, let me see, could you use [Procmon](https://docs.microsoft.com/en-us/sysinternals/downloads/procmon) to visualize all the calls to the system that the executable makes on your computer? This way we can probably detect which file is not found or the exact point where the code fails.

**Comment by DarylSun** [comment]
I ran into the same problem. Windows 10 version 1903 as well. I get this error when using the portable version.
![image](https://user-images.githubusercontent.com/46442682/67258518-a0aa0900-f480-11e9-8e24-a56eae01e946.png)

**Comment by michelolvera** [comment]
@DarylSun the problem you present is the absence of Visual C++, you can download it [here](https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads).

Let me know if this solves your problem.

**Comment by DarylSun** [comment]
@michelolvera Thank you! This has solved my issue. ghostwriter portable can run now.

**Comment by DarylSun** [comment]
I decided to install the non-portable version, and the installer attempted to install Visual C++ again. I cancelled the installation, since I already have it: should I not have done that? Would have it detected my existing installation of Visual C++?

**Comment by richo67** [comment]
> 
> 
> @DarylSun the problem you present is the absence of Visual C++, you can download it [here](https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads).
> 
> Let me know if this solves your problem.

@michelolvera which one exactly I need to download, there are so many of those packages, do you know? I installed now 1.8.1 and it is complaining about the vcruntime140_1.dll the 1.8.0 worked fine. 
I am on Win10 1909
Thanks

**Comment by michelolvera** [comment]
Download the [Microsoft Visual C++ Redistributable for Visual Studio 2015, 2017 and 2019](https://aka.ms/vs/16/release/vc_redist.x64.exe)

**Comment by SCLeoX** [comment]
> Download the [Microsoft Visual C++ Redistributable for Visual Studio 2015, 2017 and 2019](https://aka.ms/vs/16/release/vc_redist.x64.exe)

Sorry for late reply. I just installed it. and the issue persists. I still cannot open ghostwriter for some reason.

**Comment by Timecrash** [comment]
This is an issue for me, as well.

**Comment by Timecrash** [comment]
@michelolvera If it helps, I've attached a full ProcMon log of a Ghostwriter run, from start to end. I ran it as an Administrator, and I was sure to install the Visual C++ Redistributable per the readme.
[Logfile.zip](https://github.com/michelolvera/vs-ghostwriter/files/4808465/Logfile.zip)
